/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      responses: {
        /** @description User registered */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              user: {
                id: string;
                username: string;
                email: string;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Email or username already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Logged in, token set in cookie */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              user: {
                id: string;
                username: string;
                email: string;
                role: string;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Invalid credentials */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User data */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              user: components["schemas"]["UserProfile"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/image": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update profile image */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            imageUrl: string;
          };
        };
      };
      responses: {
        /** @description Image updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              updated: string;
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/users/goals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update nutrition goals */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            dailyCaloriesGoal: number;
            dailyProteinGoal: number;
            dailyCarbsGoal: number;
            dailyFatGoal: number;
          };
        };
      };
      responses: {
        /** @description Goals updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              updated: {
                id: string;
                dailyCaloriesGoal: number | null;
                dailyProteinGoal: number | null;
                dailyCarbsGoal: number | null;
                dailyFatGoal: number | null;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/users/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Logout user */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Logged out */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all products */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of products */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              products: {
                id: string;
                name: string;
                calories: number;
                carbs: number;
                protein: number;
                fat: number;
                imageUrl: string;
                createdAt: string;
              }[];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    /** Create a new product */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      responses: {
        /** @description Product created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              product: {
                id: string;
                name: string;
                calories: number;
                carbs: number;
                protein: number;
                fat: number;
                imageUrl: string;
                createdAt: string;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/products/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search products */
    get: {
      parameters: {
        query: {
          search: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Search results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              products: {
                id: string;
                name: string;
                calories: number;
                carbs: number;
                protein: number;
                fat: number;
                imageUrl: string;
                createdAt: string;
              }[];
            };
          };
        };
        /** @description Missing search term */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/products/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get product by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Product */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              product: {
                id: string;
                name: string;
                calories: number;
                carbs: number;
                protein: number;
                fat: number;
                imageUrl: string;
                createdAt: string;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Product not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete product */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Product deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              deleted: {
                id: string;
                name: string;
                calories: number;
                carbs: number;
                protein: number;
                fat: number;
                imageUrl: string;
                createdAt: string;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Product not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update product */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            calories?: number;
            carbs?: number;
            protein?: number;
            fat?: number;
            imageUrl?: string;
          };
        };
      };
      responses: {
        /** @description Product updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              product: {
                id: string;
                name: string;
                calories: number;
                carbs: number;
                protein: number;
                fat: number;
                imageUrl: string;
                createdAt: string;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Product not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/diary": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get user diary */
    get: {
      parameters: {
        query?: {
          date?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Diary entries */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              diaryEntries: {
                id: string;
                date: string;
                userId: string;
                createdAt: string;
                items: {
                  id: string;
                  diaryEntryId: string;
                  productId: string | null;
                  recipeId: string | null;
                  /** @enum {string} */
                  mealType: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK";
                  quantity: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  } | null;
                  recipe: {
                    id: string;
                    name: string;
                    products: {
                      quantity: string;
                      product: {
                        id: string;
                        name: string;
                        calories: string;
                        carbs: string;
                        protein: string;
                        fat: string;
                        imageUrl: string;
                        createdAt: string;
                      };
                    }[];
                  } | null;
                }[];
              }[];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    /** Add diary entry */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["DiaryEntry"];
        };
      };
      responses: {
        /** @description Entry added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              newDiaryEntry: {
                id: string;
                date: string;
                userId: string;
                createdAt: string;
                items: {
                  id: string;
                  diaryEntryId: string;
                  productId: string | null;
                  recipeId: string | null;
                  /** @enum {string} */
                  mealType: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK";
                  quantity: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  } | null;
                  recipe: {
                    id: string;
                    name: string;
                    products: {
                      quantity: string;
                      product: {
                        id: string;
                        name: string;
                        calories: string;
                        carbs: string;
                        protein: string;
                        fat: string;
                        imageUrl: string;
                        createdAt: string;
                      };
                    }[];
                  } | null;
                }[];
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/diary/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete diary entry */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Entry deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              deleted: {
                id: string;
                date: string;
                userId: string;
                createdAt: string;
                items: {
                  id: string;
                  diaryEntryId: string;
                  productId: string | null;
                  recipeId: string | null;
                  /** @enum {string} */
                  mealType: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK";
                  quantity: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  } | null;
                  recipe: {
                    id: string;
                    name: string;
                    products: {
                      quantity: string;
                      product: {
                        id: string;
                        name: string;
                        calories: string;
                        carbs: string;
                        protein: string;
                        fat: string;
                        imageUrl: string;
                        createdAt: string;
                      };
                    }[];
                  } | null;
                }[];
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Entry not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/diary/{id}/item": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete diary item */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Item deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              deleted: {
                id: string;
                diaryEntryId: string;
                productId: string | null;
                recipeId: string | null;
                /** @enum {string} */
                mealType: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK";
                quantity: string;
                createdAt: string;
                product: {
                  id: string;
                  name: string;
                  calories: string;
                  carbs: string;
                  protein: string;
                  fat: string;
                  imageUrl: string;
                  createdAt: string;
                } | null;
                recipe: {
                  id: string;
                  name: string;
                  products: {
                    quantity: string;
                    product: {
                      id: string;
                      name: string;
                      calories: string;
                      carbs: string;
                      protein: string;
                      fat: string;
                      imageUrl: string;
                      createdAt: string;
                    };
                  }[];
                } | null;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Item not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all recipes */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of recipes */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              recipes: {
                id: string;
                name: string;
                createdAt: string;
                products: {
                  id: string;
                  quantity: string;
                  productId: string;
                  recipeId: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  };
                }[];
              }[];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    /** Create a recipe */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Recipe"];
        };
      };
      responses: {
        /** @description Recipe created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              recipe: {
                id: string;
                name: string;
                createdAt: string;
                products: {
                  id: string;
                  quantity: string;
                  productId: string;
                  recipeId: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  };
                }[];
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recipes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get recipe by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recipe */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              recipe: {
                id: string;
                name: string;
                createdAt: string;
                products: {
                  id: string;
                  quantity: string;
                  productId: string;
                  recipeId: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  };
                }[];
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Recipe not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete recipe */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Recipe deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              deleted: {
                id: string;
                name: string;
                createdAt: string;
                products: {
                  id: string;
                  quantity: string;
                  productId: string;
                  recipeId: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  };
                }[];
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Recipe not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update recipe */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            products?: {
              /** Format: uuid */
              productId: string;
              quantity: number;
            }[];
          };
        };
      };
      responses: {
        /** @description Recipe updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              recipe: {
                id: string;
                name: string;
                createdAt: string;
                products: {
                  id: string;
                  quantity: string;
                  productId: string;
                  recipeId: string;
                  createdAt: string;
                  product: {
                    id: string;
                    name: string;
                    calories: string;
                    carbs: string;
                    protein: string;
                    fat: string;
                    imageUrl: string;
                    createdAt: string;
                  };
                }[];
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Recipe not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/recent-searches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get recent searches for the logged-in user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of recent searches */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              recentSearches: {
                id: string;
                userId: string;
                productId: string;
                createdAt: string;
                product: {
                  id: string;
                  name: string;
                  calories: number;
                  carbs: number;
                  protein: number;
                  fat: number;
                  imageUrl: string;
                  createdAt: string;
                } | null;
              }[];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    /** Add a product to recent searches */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            /** Format: uuid */
            productId: string;
          };
        };
      };
      responses: {
        /** @description Recent search added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              newRecentSearch: {
                id: string;
                userId: string;
                productId: string;
                createdAt: string;
              };
            };
          };
        };
        /** @description Invalid product ID */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/measurements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all measurements */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of measurements */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              measurements: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: date-time */
                date: string;
                weight: number | string;
                waist: number | string;
                hips: number | string;
                arm: number | string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              }[];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    /** Create a new measurement */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["Measurements"];
        };
      };
      responses: {
        /** @description Measurement created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              measurement: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: date-time */
                date: string;
                weight: number | string;
                waist: number | string;
                hips: number | string;
                arm: number | string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/measurements/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get measurement by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Measurement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              measurement: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: date-time */
                date: string;
                weight: number | string;
                waist: number | string;
                hips: number | string;
                arm: number | string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Measurement not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete measurement */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Measurement deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              deleted: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: date-time */
                date: string;
                weight: number | string;
                waist: number | string;
                hips: number | string;
                arm: number | string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Measurement not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update measurement */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            weight?: number | null;
            waist?: number | null;
            hips?: number | null;
            arm?: number | null;
          };
        };
      };
      responses: {
        /** @description Measurement updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              measurement: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: date-time */
                date: string;
                weight: number | string;
                waist: number | string;
                hips: number | string;
                arm: number | string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
        /** @description Measurement not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    User: {
      username: string;
      email: string;
      password: string;
    };
    UserProfile: {
      id: string;
      username: string;
      email: string;
      role: string;
      imageUrl: string | null;
      createdAt: string;
      updatedAt: string;
      userGoals: {
        id: string;
        dailyCaloriesGoal: number | null;
        dailyProteinGoal: number | null;
        dailyCarbsGoal: number | null;
        dailyFatGoal: number | null;
      } | null;
    };
    Product: {
      name: string;
      calories: number;
      carbs: number;
      protein: number;
      fat: number;
      imageUrl?: string;
    };
    DiaryEntry: {
      /** Format: date-time */
      date: string | null;
      /** @enum {string} */
      mealType: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK";
      /** Format: uuid */
      productId?: string;
      /** Format: uuid */
      recipeId?: string;
      quantity: number;
    };
    Recipe: {
      name: string;
      products: {
        /** Format: uuid */
        productId: string;
        quantity: number;
      }[];
    };
    Measurements: {
      weight: number | null;
      waist: number | null;
      hips: number | null;
      arm: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
